### PR TITLE
cmd/webui: create client-side parsing of ICL files

### PR DESCRIPTION
**Pull request by adamdecaf**
This PR introduces a web UI which can parse ICL files from Go->WASM cross-compiling of our library. It lets us host a tool/demo for the community. 

To run / dev locally run:
```
make build-webui && go run ./cmd/webui/
```
Then open http://localhost:8083/ in a browser. You can use [some of our test files](https://github.com/moov-io/imagecashletter/tree/master/test/testdata) as examples. 

Issue: https://github.com/moov-io/imagecashletter/issues/109

### CODE REVIEW

**Comment by adamdecaf** [comment]
@joshsadler I'm seeing something strange.. After clicking "Parse ICL File" the URL has `?jsoninput=...` appended with the file contents and the page seems to refresh clearing the input/output boxes. The parsed file response is lost.

**Comment by joshsadler** [comment]
Oh dang, I forgot to set event.preventDefault() when moving the handler from button click to form submit

**Comment by adamdecaf** [comment]
Gotcha. I added it locally and that fixes the redirect.

**Comment by adamdecaf** [comment]
Screen Shot 2020-08-16 at 7 43 43 AM

**Comment by joshsadler** [comment]
@adamdecaf good call on adding a header. I tweaked it :) 

Screen Shot 2020-08-16 at 10 02 33 AM

**Pull request merged**
